# Generated by Django 2.0.5 on 2019-08-08 00:20

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('author', models.CharField(default='佚名', max_length=255, verbose_name='作者')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('content', DjangoUeditor.models.UEditorField(error_messages={'null': '不能为空.'}, verbose_name='新闻内容')),
                ('word_num', models.IntegerField(blank=True, null=True, verbose_name='字数')),
                ('browse_num', models.IntegerField(blank=True, null=True, verbose_name='浏览数')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, unique=True, verbose_name='排序')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='level')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='附件')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='封面图片')),
                ('backup', models.CharField(blank=True, max_length=255, null=True, verbose_name='预留')),
            ],
            options={
                'verbose_name_plural': '新闻',
                'db_table': 'news_info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='新闻分类')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='封面图片')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, unique=True, verbose_name='排序')),
                ('backup', models.CharField(blank=True, max_length=255, null=True, verbose_name='预留')),
            ],
            options={
                'verbose_name_plural': '新闻分类',
                'db_table': 'news_category',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinshow.NewsCategory'),
        ),
    ]
